# Base Image
FROM node:14-alpine

#Set working directory
WORKDIR '/app'

# Install some dependencies
COPY package.json .
RUN npm install

# Copy the rest of the files
# COPY . .
# Create a volume to avoid copying the files

# Option 1: Runtime mount of workdir
# docker run \
#   -p 8081:3000 \
#   -v /app/node_modules \
#   -v $(pwd):/app \
#   kimler/reactapp


# Default command
CMD ["npm", "run", "start"]
